= ansible-role-openssl
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 2
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://galaxy.ansible.com/jonaspammer/openssl[image:https://img.shields.io/badge/available%20on%20ansible%20galaxy-jonaspammer.openssl-brightgreen[Version on Galaxy]]
// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-openssl/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-openssl/actions/workflows/ci.yml/badge.svg[Testing CI]]


An Ansible role for generating OpenSSL/x509 Certificate Files
(privatekey, csr, certificate, pkcs12).

This role is a wrapper for all related community.crypto modules. It...

* prepares the system by installing packages
* defines and uses system-specific default openssl directories (see `/vars`)
* ensures said directories exist with correct permissions
* provides ability of shared defaults (e.g. `item.default_backup`)
* makes yourself DRY (i.e. by doing `x509_certificate.privatekey_passphrase: "{{ item.privatekey_passphrase ...`)
* offers the ability to install the certificate to the Systems CA-trust store (<<openssl__system_ca_store_file>>)
  if enabled (see <<install_ca_to_system>>).


toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.

The https://galaxy.ansible.com/community/crypto[`community.crypto`-collection]
must be installed on the Ansible controller.

An up-to-date pip (i.e. >21) must be installed on the host.
Needed for installation of https://pypi.org/project/cryptography/[
`cryptography>3` through pip].

A Rust compiler must be installed on the host. Needed for installation of
https://pypi.org/project/cryptography/[cryptography>3 through pip],
if `openssl_cryptography_build_rust` is true.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

=== Role Variables to configure the installation of Cryptography
The installation of cryptography is often a pain in the ass.
I have yet to find a single exception to this rule.
It has cost me feelingly, or even really, dozens of brain-tearing hours.

The below values, and their defaults seem to do the job.

[source,yaml]
----
openssl_cryptography_prefer_binary: true
----
Defines if `--prefer-binary` is passed to the `pip install` command.

[source,yaml]
----
openssl_cryptography_build_rust: false
----
Defines if the environment-variable `CRYPTOGRAPHY_DONT_BUILD_RUST` should be set to `1` (true) or `0` (false)
while issuing the `pip install` command.


[[variables:openssl]]
=== OpenSSL

[source,yaml]
----
openssl_items: []
----
List of ssl key/csr/crt/p12's to generate.
An entry may have the following values:

[NOTE]
====
This role gives you control over nearly all variables,
but also fills-in variables on its own (e.g. relative ones like `privatekey_path`).
====

filename (Required)::
Name used for every file.

[[install_ca_to_system]]
install_ca_to_system::
_Boolean_. Defaults to `false`. +
Whether to execute steps to integrate the self signed certificate to the
the System's CA Trust Store (<<openssl__system_ca_store_file>>).

[TIP]
(Debian/Ubuntu ONLY)
Messed up / Fucked up? Try setting `install_ca_to_system_fresh` to `true`.

install_ca_to_system_fresh::
(Debian/Ubuntu ONLY)
_Boolean_. Defaults to value of `default_force` (if existent) or `false`. +
Invokes `update-ca-certificates` with `--fresh`
to remove symlinks in /etc/ssl/certs directory
(_before completely resourcing the directory using the configured CA directories and settings_).
This thus purges dead / potentially wrong or conflicting certificates.


=====
The below values can be used to set the default parameters
of every module where applicable.
See the page of any below module for documentation.

default_group::
default_owner::
default_backup::
default_selevel::
default_serole::
default_setype::
default_seuser::
default_state::
default_force::
=====

=====
Parameters used to generate OpenSSL private key ('.key')
using https://docs.ansible.com/ansible/2.9/modules/openssl_privatekey_module.html[openssl_privatekey].

`path`, `mode` and `unsafe_writes` can not be supplied.

#privatekey_backup#::
privatekey_cipher::
privatekey_curve::
privatekey_group::
privatekey_owner::
privatekey_passphrase::
_privatekey_selevel_::
_privatekey_serole_::
_privatekey_setype_::
_privatekey_seuser_::
#privatekey_size#::
#privatekey_state#::
#privatekey_type#::
=====

=====
Parameters used to generate OpenSSL Certificate Signing Request with appropriate subject information ('.csr')
using https://docs.ansible.com/ansible/2.9/modules/openssl_csr_module.html[community.crypto.openssl_csr].

`mode`, `path`, `privatekey_passphrase`, `privatekey_path` and `unsafe_writes` can not be supplied.

This role forces you to supply at-least `csr_common_name`.

csr_authority_cert_issuer::
csr_authority_cert_serial_number::
csr_authority_key_identifier::
#csr_backup#::
csr_basic_constraints::
csr_basic_constraints_critical::
#csr_common_name (Required)#::
#csr_country_name#::
csr_create_subject_key_identifier::
csr_digest::
#csr_email_address#::
csr_extended_key_usage::
csr_extended_key_usage_critical::
csr_force::
csr_group::
csr_key_usage::
csr_key_usage_critical::
csr_locality_name::
csr_ocsp_must_staple::
csr_ocsp_must_staple_critical::
#csr_organization_name#::
csr_organizational_unit_name::
csr_owner::
_csr_selevel_::
_csr_serole_::
_csr_setype_::
_csr_seuser_::
#csr_state#::
#csr_state_or_province_name#::
csr_subject::
csr_subject_alt_name::
csr_subject_alt_name_critical::
csr_subject_key_identifier::
csr_use_common_name_for_san::
=====

=====
Parameters used to generate Self Signed OpenSSL certificate ('.crt')
using https://docs.ansible.com/ansible/2.9/modules/openssl_certificate_module.html[community.crypto.openssl_certificate].

`csr_path`,  `mode`, `path`, `privatekey_passphrase` and `privatekey_path` can not be supplied.
(`privatekey_passphrase` can be supplied using `csr_privatekey_passphrase`)

This role sets `provider` to "`selfsigned`" by default.


x509cert_acme_accountkey_path::
x509cert_acme_chain::
x509cert_acme_challenge_path::
x509cert_attributes::
#x509cert_backup#::
x509cert_entrust_api_client_cert_key_path::
x509cert_entrust_api_client_cert_path::
x509cert_entrust_api_key::
x509cert_entrust_api_specification_path::
x509cert_entrust_cert_type::
x509cert_entrust_not_after::
x509cert_entrust_requester_email::
x509cert_entrust_requester_name::
x509cert_entrust_requester_phone::
x509cert_extended_key_usage::
x509cert_extended_key_usage_strict::
x509cert_force::
x509cert_group::
x509cert_has_expired::
x509cert_invalid_at::
x509cert_issuer::
x509cert_issuer_strict::
x509cert_key_usage::
x509cert_key_usage_strict::
x509cert_not_after::
x509cert_not_before::
x509cert_ownca_create_authority_key_identifier::
x509cert_ownca_create_subject_key_identifier::
x509cert_ownca_digest::
x509cert_ownca_not_after::
x509cert_ownca_not_before::
x509cert_ownca_path::
x509cert_ownca_privatekey_passphrase::
x509cert_ownca_privatekey_path::
x509cert_ownca_version::
x509cert_owner::
x509cert_provider:: Defaults to `selfsigned` in this role.
x509cert_select_crypto_backend::
_x509cert_selevel_::
_x509cert_serole_::
_x509cert_setype_::
_x509cert_seuser_::
x509cert_selfsigned_create_subject_key_identifier::
x509cert_selfsigned_digest::
#x509cert_selfsigned_not_after#::
#x509cert_selfsigned_not_before#::
x509cert_selfsigned_version::
x509cert_signature_algorithms::
#x509cert_state#::
x509cert_subject::
x509cert_subject_alt_name::
x509cert_subject_alt_name_strict::
x509cert_subject_strict::
x509cert_valid_at::
x509cert_valid_in::
x509cert_version::
=====


=====
Parameters used to generate Self Signed OpenSSL certificate ('.crt')
https://docs.ansible.com/ansible/latest/collections/community/crypto/openssl_pkcs12_module.html[community.crypto.openssl_pkcs12].

`action`, `certificate_path`, `friendly_name`, `mode`,  `path`, `privatekey_passphrase`, `privatekey_path`, `return_content` and `unsafe_writes` can not be supplied.
(`privatekey_passphrase` can be supplied using `csr_privatekey_passphrase`)

pkcs12_attributes::
pkcs12_backup::
pkcs12_force::
pkcs12_group::
pkcs12_iter_size::
pkcs12_maciter_size::
pkcs12_other_certificates::
pkcs12_other_certificates_parse_all::
pkcs12_owner::
pkcs12_passphrase::
pkcs12_select_crypto_backend::
pkcs12_selevel::
pkcs12_serole::
pkcs12_setype::
pkcs12_seuser::
pkcs12_state::
=====

=== Directory Configuration

[source,yaml]
----
openssl_directory: ~
----
If given, this sets the default for the `openssl_[key|crt|csr]_directory`.

[source,yaml]
----
openssl_key_directory: [OS-specific by default, see /vars directory]
----
This directory stores sensitive objects (`key`, `p12` and `pkcs12`).

[source,yaml]
----
openssl_crt_directory: [OS-specific by default, see /vars directory]
----
This directory stores public, non-persistent objects (`csr`).

[source,yaml]
----
openssl_csr_directory: [OS-specific by default, see /vars directory]
----
This directory stores public, persistent objects (`crt`).


[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.

[[openssl__system_ca_store_file]]
.`openssl__system_ca_store_file`
****
Location of the System's trusted CA Certificate Store/Bundle File.
As per https://serverfault.com/a/722646
****


[[tags]]
== 🏷️ Tags

// Checkout https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/roles/server/README.md#tags
// for an awesome example of grouping tasks using tags

Tasks are tagged with the following
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#adding-tags-to-roles[tags]:

[cols="1,1"]
|===
|Tag | Purpose

2+| This role does not have officially documented tags yet.

// | download-xyz
// |
// | install-prerequisites
// |
// | install
// |
// | create-xyz
// |
|===

You can use Ansible to skip tasks, or only run certain tasks by using these tags. By default, all tasks are run when no tags are specified.


[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/resources/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/resources/prepare.yml[]
[source,yaml]
----
include::molecule/resources/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_openssl.svg[
requirements.yml dependency graph of jonaspammer.openssl]
====

.Common Play / OpenSSL Item
====
[source,yaml]
----
roles:
  - jonaspammer.openssl

vars:
  - filename: common_jonaspammer_at
    csr_common_name: common.jonaspammer.at
    csr_country_name: "AT"
    csr_state_or_province_name: "Vorarlberg"
    csr_locality_name: "Bregenz"
    csr_email_address: "opensource@jonaspammer.at"

    privatekey_backup: true
    install_ca_to_system: true
----
====


.Minimum Viable Play / OpenSSL Item
====
* The following play:
+
[source,yaml]
----
roles:
  - jonaspammer.openssl

vars:
  openssl_items:
    - filename: jonaspammer_at
      csr_common_name: jonaspammer.at
----
+
creates the following files (on Debian):
+
----
root@instance-py3-ansible-5-ubuntu1604:/# ls -l /etc/ssl/private/ # openssl_key_directory
total 16
-rw------- 1 root root 3243 Jun 23 09:37 jonaspammer_at.key
-rw-r----- 1 root root 5031 Jun 23 09:37 jonaspammer_at.keycrt
-rw-r----- 1 root root 4024 Jun 23 09:37 jonaspammer_at.p12

root@instance-py3-ansible-5-ubuntu1604:/# ls -l /etc/ssl/misc # openssl_csr_directory
total 4
-rw-r--r-- 1 root root 1651 Jun 23 09:37 jonaspammer_at.csr

root@instance-py3-ansible-5-ubuntu1604:/# ls -l /etc/ssl/certs # openssl_crt_directory
total 580
lrwxrwxrwx 1 root root     49 Sep 19  2021 01419da9.0 -> Microsoft_ECC_Root_Certificate_Authority_2017.pem
lrwxrwxrwx 1 root root     45 Sep 19  2021 02265526.0 -> Entrust_Root_Certification_Authority_-_G2.pem
…
-rw-r--r-- 1 root root   1789 Jun 23 09:37 jonaspammer_at.crt
…

# Below commands as seen in https://www.xolphin.com/support/OpenSSL/Frequently_used_OpenSSL_Commands

root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl x509 -text -noout -in certs/jonaspammer_at.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0a:03:4d:1e:db:b5:48:d2:13:d8:1c:d5:28:46:41:1d:7c:1c:f1:7f
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=jonaspammer.at
        Validity
            Not Before: Jun 23 09:37:25 2022 GMT
            Not After : Jun 20 09:37:25 2032 GMT
        Subject: CN=jonaspammer.at
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:cf:62:15:5b:cb:3e:3a:7c:3a:9b:5e:5e:47:37:
                    ………
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:jonaspammer.at
            X509v3 Subject Key Identifier:
                6C:5E:12:CE:E1:98:4C:F1:B4:74:4E:AB:C4:1E:93:15:69:79:72:3B
    Signature Algorithm: sha256WithRSAEncryption
         21:f6:11:83:83:15:01:62:e2:78:8e:78:44:cd:0e:8c:01:00:
         ………

root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl req -text -noout -verify -in misc/jonaspammer_at.csr
verify OK
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=jonaspammer.at
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
                Modulus:
                    00:cf:62:15:5b:cb:3e:3a:7c:3a:9b:5e:5e:47:37:
                    ………
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:jonaspammer.at
    Signature Algorithm: sha256WithRSAEncryption
         81:09:f3:cf:55:3c:ef:2f:6c:b7:5e:cd:64:d0:66:f5:1d:d4:
         ………

root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl rsa -noout -in private/jonaspammer_at.key -check
RSA key ok

root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl pkcs12 -noout -info -in private/jonaspammer_at.p12
Enter Import Password:
MAC Iteration 1
MAC verified OK
PKCS7 Data
Certificate bag
PKCS7 Data
Key bag

# Checking the MD5 hash of the public key to check if it is equal to what is in the CSR or private key.
root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl x509 -noout -modulus -in certs/jonaspammer_at.crt | openssl md5
-in private/jonaspammer_at.key | openssl md5
opens(stdin)= da1f0a7e379330443660f098bfb64043
root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl rsa -noout -modulus -in private/jonaspammer_at.key | openssl md5
sl req -noout -modulus -in misc/jonaspammer_at.csr(stdin)= da1f0a7e379330443660f098bfb64043
root@instance-py3-ansible-5-ubuntu1604:/etc/ssl# openssl req -noout -modulus -in misc/jonaspammer_at.csr | openssl md5
(stdin)= da1f0a7e379330443660f098bfb64043
----
====

[[development]]
== 📝 Development
// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-openssl/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-openssl/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]
https://open.vscode.dev/JonasPammer/ansible-role-openssl[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]

include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-openssl/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-openssl/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
