---
# tasks file for testing that variables of ansible-role jonaspammer.openssl are set correctly
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html

- when: openssl_items is defined
  block:
    - name: test if 'openssl_items' is a list
      ansible.builtin.assert:
        that:
          - openssl_items is iterable
        quiet: true
    - name: test if each item of 'openssl_items' has most-necessary values defined
      ansible.builtin.assert:
        that:
          - item.filename is defined
          - item.csr_common_name is defined
        quiet: true
      loop: "{{ openssl_items }}"

- name: test if 'openssl_key_directory' is set correctly
  ansible.builtin.assert:
    that:
      - openssl_key_directory is defined
      - openssl_key_directory is string
    quiet: true

- name: test if 'openssl_csr_directory' is set correctly
  ansible.builtin.assert:
    that:
      - openssl_csr_directory is defined
      - openssl_csr_directory is string
    quiet: true

- name: test if 'openssl_crt_directory' is set correctly
  ansible.builtin.assert:
    that:
      - openssl_crt_directory is defined
      - openssl_crt_directory is string
    quiet: true
