---
- name: Converge
  hosts: all

  vars:
    openssl_items:
      # as per minimum viable playbook example:
      - filename: mvp_simple_at
        csr_common_name: mvp.simple.at
      # as per common playbook example:
      - filename: common_jonaspammer_at
        csr_common_name: common.jonaspammer.at
        csr_country_name: "AT"
        csr_state_or_province_name: "Vorarlberg"
        csr_locality_name: "Bregenz"
        csr_email_address: "opensource@jonaspammer.at"

        privatekey_backup: true
        install_ca_to_system: true

  roles:
    - name: "ansible-role-openssl"
